# Generated by Django 4.1.5 on 2023-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartmentsforrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('city', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url', models.URLField(verbose_name='Ссылка на обьявление')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Аренда квартир',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('city', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url', models.URLField(verbose_name='Ссылка на обьявление')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Продажа авто',
            },
        ),
        migrations.CreateModel(
            name='Saleofapartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('city', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url', models.URLField(verbose_name='Ссылка на обьявление')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Продажа квартир',
            },
        ),
    ]
